/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as SkillSlugRouteImport } from './routes/skill.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillSlugRoute = SkillSlugRouteImport.update({
  id: '/skill/$slug',
  path: '/skill/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/skill/$slug': typeof SkillSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/skill/$slug': typeof SkillSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/skill/$slug': typeof SkillSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skills' | '/category/$slug' | '/skill/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills' | '/category/$slug' | '/skill/$slug'
  id: '__root__' | '/' | '/skills' | '/category/$slug' | '/skill/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsRoute: typeof SkillsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  SkillSlugRoute: typeof SkillSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$slug': {
      id: '/skill/$slug'
      path: '/skill/$slug'
      fullPath: '/skill/$slug'
      preLoaderRoute: typeof SkillSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsRoute: SkillsRoute,
  CategorySlugRoute: CategorySlugRoute,
  SkillSlugRoute: SkillSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
